const selCourseData = <Array<Object>>[
  {
    orderBook: "",
    courseName: "就业准备与应聘技巧",
    courseNumber: "9001601000",
    teacherName: "刘琳",
    classTime: "周一第10,11,12节{第4-15周}",
    classLocation: "5107（多媒体）",
    credit: "2",
    weekHour: "3.0-0.0",
    startEndWeek: "04-15",
    count: "100",
    margin: "1",
    courseOwner: "校公共选修课",
    curriculum: "校公共选修课",
    campusNumber: "江宁校区",
    college: "商学院",
    examTime: ""
  },
  {
    orderBook: "",
    courseName: "就业准备与应聘技巧",
    courseNumber: "9001601000",
    teacherName: "刘琳",
    classTime: "周一第10,11,12节{第4-15周}",
    classLocation: "5107（多媒体）",
    credit: "2",
    weekHour: "3.0-0.0",
    startEndWeek: "04-15",
    count: "100",
    margin: "1",
    courseOwner: "校公共选修课",
    curriculum: "校公共选修课",
    campusNumber: "江宁校区",
    college: "商学院",
    examTime: ""
  },
  {
    orderBook: "",
    courseName: "就业准备与应聘技巧",
    courseNumber: "9001601000",
    teacherName: "刘琳",
    classTime: "周一第10,11,12节{第4-15周}",
    classLocation: "5107（多媒体）",
    credit: "2",
    weekHour: "3.0-0.0",
    startEndWeek: "04-15",
    count: "100",
    margin: "1",
    courseOwner: "校公共选修课",
    curriculum: "校公共选修课",
    campusNumber: "江宁校区",
    college: "商学院",
    examTime: ""
  },
  {
    orderBook: "",
    courseName: "就业准备与应聘技巧",
    courseNumber: "9001601000",
    teacherName: "刘琳",
    classTime: "周一第10,11,12节{第4-15周}",
    classLocation: "5107（多媒体）",
    credit: "2",
    weekHour: "3.0-0.0",
    startEndWeek: "04-15",
    count: "100",
    margin: "1",
    courseOwner: "校公共选修课",
    curriculum: "校公共选修课",
    campusNumber: "江宁校区",
    college: "商学院",
    examTime: ""
  },
  {
    orderBook: "",
    courseName: "就业准备与应聘技巧",
    courseNumber: "9001601000",
    teacherName: "刘琳",
    classTime: "周一第10,11,12节{第4-15周}",
    classLocation: "5107（多媒体）",
    credit: "2",
    weekHour: "3.0-0.0",
    startEndWeek: "04-15",
    count: "100",
    margin: "1",
    courseOwner: "校公共选修课",
    curriculum: "校公共选修课",
    campusNumber: "江宁校区",
    college: "商学院",
    examTime: ""
  },
  {
    orderBook: "",
    courseName: "就业准备与应聘技巧",
    courseNumber: "9001601000",
    teacherName: "刘琳",
    classTime: "周一第10,11,12节{第4-15周}",
    classLocation: "5107（多媒体）",
    credit: "2",
    weekHour: "3.0-0.0",
    startEndWeek: "04-15",
    count: "100",
    margin: "1",
    courseOwner: "校公共选修课",
    curriculum: "校公共选修课",
    campusNumber: "江宁校区",
    college: "商学院",
    examTime: ""
  },
  {
    orderBook: "",
    courseName: "就业准备与应聘技巧",
    courseNumber: "9001601000",
    teacherName: "刘琳",
    classTime: "周一第10,11,12节{第4-15周}",
    classLocation: "5107（多媒体）",
    credit: "2",
    weekHour: "3.0-0.0",
    startEndWeek: "04-15",
    count: "100",
    margin: "1",
    courseOwner: "校公共选修课",
    curriculum: "校公共选修课",
    campusNumber: "江宁校区",
    college: "商学院",
    examTime: ""
  },
  {
    orderBook: "",
    courseName: "就业准备与应聘技巧",
    courseNumber: "9001601000",
    teacherName: "刘琳",
    classTime: "周一第10,11,12节{第4-15周}",
    classLocation: "5107（多媒体）",
    credit: "2",
    weekHour: "3.0-0.0",
    startEndWeek: "04-15",
    count: "100",
    margin: "1",
    courseOwner: "校公共选修课",
    curriculum: "校公共选修课",
    campusNumber: "江宁校区",
    college: "商学院",
    examTime: ""
  },
  {
    orderBook: "",
    courseName: "就业准备与应聘技巧",
    courseNumber: "9001601000",
    teacherName: "刘琳",
    classTime: "周一第10,11,12节{第4-15周}",
    classLocation: "5107（多媒体）",
    credit: "2",
    weekHour: "3.0-0.0",
    startEndWeek: "04-15",
    count: "100",
    margin: "1",
    courseOwner: "校公共选修课",
    curriculum: "校公共选修课",
    campusNumber: "江宁校区",
    college: "商学院",
    examTime: ""
  },
  {
    orderBook: "",
    courseName: "就业准备与应聘技巧",
    courseNumber: "9001601000",
    teacherName: "刘琳",
    classTime: "周一第10,11,12节{第4-15周}",
    classLocation: "5107（多媒体）",
    credit: "2",
    weekHour: "3.0-0.0",
    startEndWeek: "04-15",
    count: "100",
    margin: "1",
    courseOwner: "校公共选修课",
    curriculum: "校公共选修课",
    campusNumber: "江宁校区",
    college: "商学院",
    examTime: ""
  },
  {
    orderBook: "",
    courseName: "就业准备与应聘技巧",
    courseNumber: "9001601000",
    teacherName: "刘琳",
    classTime: "周一第10,11,12节{第4-15周}",
    classLocation: "5107（多媒体）",
    credit: "2",
    weekHour: "3.0-0.0",
    startEndWeek: "04-15",
    count: "100",
    margin: "1",
    courseOwner: "校公共选修课",
    curriculum: "校公共选修课",
    campusNumber: "江宁校区",
    college: "商学院",
    examTime: ""
  },
  {
    orderBook: "",
    courseName: "就业准备与应聘技巧",
    courseNumber: "9001601000",
    teacherName: "刘琳",
    classTime: "周一第10,11,12节{第4-15周}",
    classLocation: "5107（多媒体）",
    credit: "2",
    weekHour: "3.0-0.0",
    startEndWeek: "04-15",
    count: "100",
    margin: "1",
    courseOwner: "校公共选修课",
    curriculum: "校公共选修课",
    campusNumber: "江宁校区",
    college: "商学院",
    examTime: ""
  },
  {
    orderBook: "",
    courseName: "就业准备与应聘技巧",
    courseNumber: "9001601000",
    teacherName: "刘琳",
    classTime: "周一第10,11,12节{第4-15周}",
    classLocation: "5107（多媒体）",
    credit: "2",
    weekHour: "3.0-0.0",
    startEndWeek: "04-15",
    count: "100",
    margin: "1",
    courseOwner: "校公共选修课",
    curriculum: "校公共选修课",
    campusNumber: "江宁校区",
    college: "商学院",
    examTime: ""
  },
  {
    orderBook: "",
    courseName: "就业准备与应聘技巧",
    courseNumber: "9001601000",
    teacherName: "刘琳",
    classTime: "周一第10,11,12节{第4-15周}",
    classLocation: "5107（多媒体）",
    credit: "2",
    weekHour: "3.0-0.0",
    startEndWeek: "04-15",
    count: "100",
    margin: "1",
    courseOwner: "校公共选修课",
    curriculum: "校公共选修课",
    campusNumber: "江宁校区",
    college: "商学院",
    examTime: ""
  },
  {
    orderBook: "",
    courseName: "就业准备与应聘技巧",
    courseNumber: "9001601000",
    teacherName: "刘琳",
    classTime: "周一第10,11,12节{第4-15周}",
    classLocation: "5107（多媒体）",
    credit: "2",
    weekHour: "3.0-0.0",
    startEndWeek: "04-15",
    count: "100",
    margin: "1",
    courseOwner: "校公共选修课",
    curriculum: "校公共选修课",
    campusNumber: "江宁校区",
    college: "商学院",
    examTime: ""
  },
  {
    orderBook: "",
    courseName: "就业准备与应聘技巧",
    courseNumber: "9001601000",
    teacherName: "刘琳",
    classTime: "周一第10,11,12节{第4-15周}",
    classLocation: "5107（多媒体）",
    credit: "2",
    weekHour: "3.0-0.0",
    startEndWeek: "04-15",
    count: "100",
    margin: "1",
    courseOwner: "校公共选修课",
    curriculum: "校公共选修课",
    campusNumber: "江宁校区",
    college: "商学院",
    examTime: ""
  },
  {
    orderBook: "",
    courseName: "就业准备与应聘技巧",
    courseNumber: "9001601000",
    teacherName: "刘琳",
    classTime: "周一第10,11,12节{第4-15周}",
    classLocation: "5107（多媒体）",
    credit: "2",
    weekHour: "3.0-0.0",
    startEndWeek: "04-15",
    count: "100",
    margin: "1",
    courseOwner: "校公共选修课",
    curriculum: "校公共选修课",
    campusNumber: "江宁校区",
    college: "商学院",
    examTime: ""
  },
  {
    orderBook: "",
    courseName: "就业准备与应聘技巧",
    courseNumber: "9001601000",
    teacherName: "刘琳",
    classTime: "周一第10,11,12节{第4-15周}",
    classLocation: "5107（多媒体）",
    credit: "2",
    weekHour: "3.0-0.0",
    startEndWeek: "04-15",
    count: "100",
    margin: "1",
    courseOwner: "校公共选修课",
    curriculum: "校公共选修课",
    campusNumber: "江宁校区",
    college: "商学院",
    examTime: ""
  },
  {
    orderBook: "",
    courseName: "就业准备与应聘技巧",
    courseNumber: "9001601000",
    teacherName: "刘琳",
    classTime: "周一第10,11,12节{第4-15周}",
    classLocation: "5107（多媒体）",
    credit: "2",
    weekHour: "3.0-0.0",
    startEndWeek: "04-15",
    count: "100",
    margin: "1",
    courseOwner: "校公共选修课",
    curriculum: "校公共选修课",
    campusNumber: "江宁校区",
    college: "商学院",
    examTime: ""
  },
  {
    orderBook: "",
    courseName: "就业准备与应聘技巧",
    courseNumber: "9001601000",
    teacherName: "刘琳",
    classTime: "周一第10,11,12节{第4-15周}",
    classLocation: "5107（多媒体）",
    credit: "2",
    weekHour: "3.0-0.0",
    startEndWeek: "04-15",
    count: "100",
    margin: "1",
    courseOwner: "校公共选修课",
    curriculum: "校公共选修课",
    campusNumber: "江宁校区",
    college: "商学院",
    examTime: ""
  },
  {
    orderBook: "",
    courseName: "就业准备与应聘技巧",
    courseNumber: "9001601000",
    teacherName: "刘琳",
    classTime: "周一第10,11,12节{第4-15周}",
    classLocation: "5107（多媒体）",
    credit: "2",
    weekHour: "3.0-0.0",
    startEndWeek: "04-15",
    count: "100",
    margin: "1",
    courseOwner: "校公共选修课",
    curriculum: "校公共选修课",
    campusNumber: "江宁校区",
    college: "商学院",
    examTime: ""
  },
  {
    orderBook: "",
    courseName: "就业准备与应聘技巧",
    courseNumber: "9001601000",
    teacherName: "刘琳",
    classTime: "周一第10,11,12节{第4-15周}",
    classLocation: "5107（多媒体）",
    credit: "2",
    weekHour: "3.0-0.0",
    startEndWeek: "04-15",
    count: "100",
    margin: "1",
    courseOwner: "校公共选修课",
    curriculum: "校公共选修课",
    campusNumber: "江宁校区",
    college: "商学院",
    examTime: ""
  },
  {
    orderBook: "",
    courseName: "就业准备与应聘技巧",
    courseNumber: "9001601000",
    teacherName: "刘琳",
    classTime: "周一第10,11,12节{第4-15周}",
    classLocation: "5107（多媒体）",
    credit: "2",
    weekHour: "3.0-0.0",
    startEndWeek: "04-15",
    count: "100",
    margin: "1",
    courseOwner: "校公共选修课",
    curriculum: "校公共选修课",
    campusNumber: "江宁校区",
    college: "商学院",
    examTime: ""
  },
  {
    orderBook: "",
    courseName: "就业准备与应聘技巧",
    courseNumber: "9001601000",
    teacherName: "刘琳",
    classTime: "周一第10,11,12节{第4-15周}",
    classLocation: "5107（多媒体）",
    credit: "2",
    weekHour: "3.0-0.0",
    startEndWeek: "04-15",
    count: "100",
    margin: "1",
    courseOwner: "校公共选修课",
    curriculum: "校公共选修课",
    campusNumber: "江宁校区",
    college: "商学院",
    examTime: ""
  },
  {
    orderBook: "",
    courseName: "就业准备与应聘技巧",
    courseNumber: "9001601000",
    teacherName: "刘琳",
    classTime: "周一第10,11,12节{第4-15周}",
    classLocation: "5107（多媒体）",
    credit: "2",
    weekHour: "3.0-0.0",
    startEndWeek: "04-15",
    count: "100",
    margin: "1",
    courseOwner: "校公共选修课",
    curriculum: "校公共选修课",
    campusNumber: "江宁校区",
    college: "商学院",
    examTime: ""
  },
  {
    orderBook: "",
    courseName: "就业准备与应聘技巧",
    courseNumber: "9001601000",
    teacherName: "刘琳",
    classTime: "周一第10,11,12节{第4-15周}",
    classLocation: "5107（多媒体）",
    credit: "2",
    weekHour: "3.0-0.0",
    startEndWeek: "04-15",
    count: "100",
    margin: "1",
    courseOwner: "校公共选修课",
    curriculum: "校公共选修课",
    campusNumber: "江宁校区",
    college: "商学院",
    examTime: ""
  },
  {
    orderBook: "",
    courseName: "就业准备与应聘技巧",
    courseNumber: "9001601000",
    teacherName: "刘琳",
    classTime: "周一第10,11,12节{第4-15周}",
    classLocation: "5107（多媒体）",
    credit: "2",
    weekHour: "3.0-0.0",
    startEndWeek: "04-15",
    count: "100",
    margin: "1",
    courseOwner: "校公共选修课",
    curriculum: "校公共选修课",
    campusNumber: "江宁校区",
    college: "商学院",
    examTime: ""
  }
];

const selectedData = <Array<Object>>[
  {
    courseName: "就业准备与应聘技巧",
    teacherName: "刘琳",
    credit: "2",
    weekHour: "3.0-0.0",
    startEndWeek: "04-15",
    campus: "江宁校区",
    classTime: "周一第10,11,12节{第4-15周}",
    classLocation: "5107（多媒体）",
    orderBook: "否",
    courseOwner: "校公共选修课",
    curriculum: "校公共选修课",
    campusNumber: "江宁校区"
  },
  {
    courseName: "就业准备与应聘技巧",
    teacherName: "刘琳",
    credit: "2",
    weekHour: "3.0-0.0",
    startEndWeek: "04-15",
    campus: "江宁校区",
    classTime: "周一第10,11,12节{第4-15周}",
    classLocation: "5107（多媒体）",
    orderBook: "否",
    courseOwner: "校公共选修课",
    curriculum: "校公共选修课",
    campusNumber: "江宁校区"
  },
  {
    courseName: "就业准备与应聘技巧",
    teacherName: "刘琳",
    credit: "2",
    weekHour: "3.0-0.0",
    startEndWeek: "04-15",
    campus: "江宁校区",
    classTime: "周一第10,11,12节{第4-15周}",
    classLocation: "5107（多媒体）",
    orderBook: "否",
    courseOwner: "校公共选修课",
    curriculum: "校公共选修课",
    campusNumber: "江宁校区"
  }
];
export { selCourseData, selectedData };
